### ISSUE TITLE
Additional empty lines while printing unsupported file formats

### ISSUE THREAD

**Issue by muhammad-abbady** [OmarTawfik/vscat#5]
Here is a comparison between `vscat` and `cat` explaining the problem:

![tempsnip](https://user-images.githubusercontent.com/7060180/126905161-1ccc1458-17b5-4f0a-a115-f5a3b907993c.png)

**Comment by OmarTawfik** [comment]
I think it is not detecting your terminal width correctly, thus not trimming it to the correct width. I'll look into it! thanks for filing.
